#ifndef TESTINGLIB_GLOBAL_H
#define TESTINGLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TESTINGLIB_LIBRARY)
#define RALLYPLOT_EXPORT Q_DECL_EXPORT
#else
#define RALLYPLOT_EXPORT Q_DECL_IMPORT
#endif

#endif // TESTINGLIB_GLOBAL_H
